---
title: My contribution to Bayes@Lund2018
authors:
- admin
date: "2018-04-10"
lastmod: "2018-04-10"
tags: ["R Markdown", "brms", "xaringan"]
categories: ["R"]
summary: "Slides of my presentation at Bayes@Lund2018."
output:
  blogdown::html_page:
    toc: no
    number_sections: no
featured: no
image:
  caption: ""
  focal_point: ""
  preview_only: yes
projects: []
editor_options: 
  chunk_output_type: console
---

In this blog post you will find the slides that accompany my presentation at [Bayes@Lund2018](https://bayesat.github.io/lund2018/bayes_at_lund_2018.html) (April 12th, 2018, Lund, Sweden).   
   
This is my first slide deck completely created in RStudio with the fantastic package [```xaringan```](https://slides.yihui.name/xaringan/#1), created by [Yihui Xie](https://github.com/yihui). Hopefully I will not sound arrogant if I say that I am quite pleased with it. I spent a long time fiddling with the *.css* files in order to create a template containing the mandatory logos of [Ghent University](https://www.ugent.be/en) and the [Faculty of Psychology and Educational Sciences](https://www.ugent.be/pp/en). It may not match any of the [official templates](https://styleguide.ugent.be/templates/digital.html#presentation-slides), but it is simple and uncluttered while displaying all the necessary information.   
   
If you browse my website, you will notice that this is also the first time that I embed slides in a blog post. It was not difficult, thanks to the clear instructions in the [blogdown book](https://bookdown.org/yihui/blogdown/). I also got inspiration from the source code of [this blog post](https://alison.rbind.io/post/r-ladies-slides/) by Alison Presmanes Hill. Thanks to all these authors for making my life considerably easier!   
   
Without further ado, here are the slides. The source code can be found on [GitHub](https://github.com/aschetti/Bayes-Lund-2018).  If something is unclear, I could also publish a draft of the speech given during each slide, similarly to what I do when creating presentations in PowerPoint (see examples [here](https://osf.io/6kny7/))[^1].

```{r echo = FALSE}

knitr::include_url('/slides/2018.04.12_BayesAtLund/Schettino_BayesAtLund2018.html')

```

[^1]: I admit it: this is also a pathetic attempt at encouraging comments on this otherwise desolate barren land of a blog.


